### ISSUE TITLE
Add-on no longer available on Mozilla website

### ISSUE THREAD

**Issue by Nicholas-Steel** [nextgens/anti-paywall#109]
https://addons.mozilla.org/addon/anti-paywall is a dead link and searching their site for the add-on doesn't show it either. Are you able to provide the XPI file?

**Comment by nextgens** [comment]
Yeah, it got pulled from both chrome's and mozilla's...

"It appears that your Add-on violates the Firefox Add-on Distribution Agreement and the Conditions of Use. Both prohibit Add-ons that violate the law. Your Add-on appears to be designed and promoted to allow users to circumvent paywalls, which is illegal.

This email is to notify you that we will remove your Add-on from addons.mozilla.org one week from the date of this email. Please feel free to contact us with questions or concerns by replying to this email."

I've asked which laws...

"There are various laws in the US that prohibit tools for circumventing access controls like a paywall. Both Section 1201 of the Digital Millennium Copyright Act (DMCA) and the Computer Fraud and Abuse Act (CFAA) are examples. 

We are responding to a specific complaint that named multiple paywall bypassing add-ons. It did not target only your add-on.
"

I am not sure what to do from there... providing XPI files won't help most users... and would probably make me a target from the said complainants.

**Comment by nextgens** [comment]
Oh, and for the record, extensions are just ZIP files... download and rename 
https://github.com/nextgens/anti-paywall/archive/master.zip if that's what you need ;)

**Comment by Nicholas-Steel** [comment]
If I change the extension for that to XPI than Firefox says it's corrupt, is that one you linked to for Chrome?

**Comment by Gertbucket** [comment]
Same here. I don't think you can sideload extensions to Firefox anymore, except in the Developers Edition. 

There are a couple of outstanding Pull Requests: not sure if they'll still be updated now that the exension is pulled from the store. Could you please merge them so we can check?

Thanks

**Comment by Nicholas-Steel** [comment]
You can still install them without needing them to be on the Mozilla add-on website, see jrwhite's post for this alternative add-on for example: https://github.com/iamadamdev/bypass-paywalls-firefox/issues/82#issuecomment-441105276

**Comment by Gertbucket** [comment]
Yes, that one installed no problem. So why doesn't the one above?

**Comment by Nicholas-Steel** [comment]
No clue.

**Comment by TRudess** [comment]
> 
> 
> Oh, and for the record, extensions are just ZIP files... download and rename
> https://github.com/nextgens/anti-paywall/archive/master.zip if that's what you need ;)

Are you able to upload the XPI file somehwere? you can add a txt extension which can later be removed after the file is downloaded.

**Comment by TRudess** [comment]
> 
> 
> If I change the extension for that to XPI than Firefox says it's corrupt, is that one you linked to for Chrome?

Yes I think it is for Chrome, it's version 0.9 , while the last version for firefox was 0.92 . Will be good if nextgens can upload the firefox version

**Comment by wle8300** [comment]
@nextgens Hi thx for this!

Can you update the README with directions to install this manually (via downloading zip)?

**Comment by TRudess** [comment]
> 
> 
> The files need to be at root of the zip file. Here. Try this. Remove txt extension.
> [antipaywall.xpi.txt](https://github.com/nextgens/anti-paywall/files/2637003/antipaywall.xpi.txt)

Thank you for that.  Is that for Firefox or Chrome?

**Comment by wle8300** [comment]
> If I change the extension for that to XPI than Firefox says it's corrupt, is that one you linked to for Chrome?

Same here. It's corrupted for me. I'm using a Mac.

**Comment by TRudess** [comment]
> 
> 
> > If I change the extension for that to XPI than Firefox says it's corrupt, is that one you linked to for Chrome?
> 
> Same here. It's corrupted for me. I'm using a Mac.

Try changing the file extension to zip

**Comment by flypenguin** [comment]
Both don't work for me, neither as XPI nor as ZIP. :(

**Comment by TRudess** [comment]
> 
> 
> Both don't work for me, neither as XPI nor as ZIP. :(

I managed to install both, but they don't work when I browse The Times for example. What other news sites it supposed to work on?

**Comment by myBestSoftAndPref** [comment]
My suggestion how to bypass the addon blocking is [here](https://github.com/iamadamdev/bypass-paywalls-firefox/issues/88)

**Comment by nextgens** [comment]
@myBestSoftAndPref I don't want to start a war with the browsers ... I just wish they let us side-load things in a sane way

**Comment by nextgens** [comment]
@TRudess clear your browsing history for the said sites... and if that doesn't work fill in a different issue please.

**Comment by nextgens** [comment]
I've now created a release (uploaded what was signed by Mozilla)...

https://github.com/nextgens/anti-paywall/releases/

**Comment by n-o-o-b** [comment]
I get the message "the add-on could not be downloaded due to a connection failiure" when trying to install from the Releases page.

**Comment by julian-alarcon** [comment]
Related info: https://github.com/mozilla/addons/issues/12763
