### ISSUE TITLE
Audio Distortion on NY Times

### ISSUE THREAD

**Issue by yoasif** [nextgens/anti-paywall#25]
Steps to reproduce:

1. Install add-on on Firefox stable or Nightly
2. Navigate to: https://www.nytimes.com/2017/11/25/us/politics/trump-roy-moore-mcconnell-alabama-senate.html

What happens:

The video that plays has a very bad distortion.

Expected result:

No distortion.

FWIW, when changing my browser UA to:

Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) 

using another add-on, I can reproduce the issue, so NYT may simply be serving up a bad stream given this UA. Hoping that there may be something that can be done to work around the issue, or at least logged as a known issue.

**Comment by nextgens** [comment]
This should be now fixed in 0.9.1
