### ISSUE TITLE
Version 0.9.1 breaks The Times

### ISSUE THREAD

**Issue by defrilitus** [nextgens/anti-paywall#26]
Version 0.9.1 doesn't work on thetimes.co.uk. on either Chrome and Firefox.
I've gone back to version 0.9, which still works perfectly with both.

**Comment by ldwoo** [comment]
Hi,

I have experienced the same with technologyreview.com, ft.com and wsj.com.
It seems to be affecting all websites.

**Comment by msft013** [comment]
Yep lots of sites are broken for me too.

**Comment by nextgens** [comment]
Hmm, sorry about that. I have screwed up while releasing it... 0.9.2 should fix it

**Comment by defrilitus** [comment]
Fixed. Thank you!
