### ISSUE TITLE
Latest version not working on thetimes.co.uk

### ISSUE THREAD

**Issue by Elsewhereman** [nextgens/anti-paywall#27]
Version 0.9.2 on Firefox 57.0.2 doesn't work on thetimes.co.uk - reverted to 0.9, which still works.

**Comment by defrilitus** [comment]
Version 0.9.1 didn't work on thetimes.co.uk, but 0.9.2 fixed the problem for me.

**Comment by nextgens** [comment]
@Elsewhereman do you have a specific URL that you can share? I can't reproduce it.

Please double-check that you are running 0.9.2 :)

**Comment by Elsewhereman** [comment]
Just manually updated to 0.9.2 again and now working! I had also been trying to find a memory leak yesterday and had disabled the I don't care about Cookies extension, so that may have some bearing on this. (Memory leak actually seems to be in Stylish!) Or maybe some fault in the updating? It usually asks me for new permissions on auto-update, but didn't this time.
