### ISSUE TITLE
Add medium.com

### ISSUE THREAD

**Issue by rochakagrawal** [nextgens/anti-paywall#3]
lovely extension works well in chrome.. I wish there was a safari extension as that's my main browser on Mac

Please also add medium.com in paywall bypass

Thank you

**Comment by uBlock-user** [comment]
Was featured in ghacks article - https://www.ghacks.net/2017/12/11/bypass-paywalls-with-anti-paywall-for-firefox-and-chrome/

**Comment by nextgens** [comment]
It will be part of next release (0.8)

**Comment by rochakagrawal** [comment]
Great - thanks. When will the release go?

**Comment by rochakagrawal** [comment]
I see you have already added medium.com on the extension homepage? Can I download it right away?

**Comment by nextgens** [comment]
It's been submitted; it's pending review... soon(TM)

**Comment by rochakagrawal** [comment]
Thanks for adding quickly - the extension 0.8. just went live in Chrome

Seems the extension works by blocking cookies. The only issue with that is that it doesn't allow a person to login with their account credentials and see personalised content. Is it possible to bypass paywall while retaining ability to login in via facebook/google on medium.com 

Thank you?

**Comment by nextgens** [comment]
No, it's not possible. You are either logged-in or bypassing the paywal ;)

**Comment by rochakagrawal** [comment]
Ok Thanks !!
