### ISSUE TITLE
The Age not bypassed in Chrome

### ISSUE THREAD

**Issue by XeonNAS** [nextgens/anti-paywall#31]
This was working in Firefox which I have had to uninstall, added the extension to Chrome and theage.com.au paywall is not being bypassed.

**Comment by nextgens** [comment]
This is weird; have you tried clearing your browsing data?

**Comment by XeonNAS** [comment]
Yeah tried that, cleared full cache, cookies the lot. Still not bypassing.

**Comment by XeonNAS** [comment]
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by nextgens** [comment]
Do you have an example URL you can share? I still can't reproduce it.

Is it all articles or just a few specific ones?

**Comment by XeonNAS** [comment]
It is pretty much all of them, for example http://www.theage.com.au/sport/tennis/arrogant-tool-tennis-greats-and-fans-turn-on-bernard-tomic-after-australian-open-spray-20180114-h0i854.html

The attached screen shot indicates that the bypass icon is greyed out? Not sure that is normal?

![image](https://user-images.githubusercontent.com/14171669/34921337-b5008f94-f9d4-11e7-9a58-04ba522823fc.png)

**Comment by nextgens** [comment]
I can't reproduce it, it loads fine for me (both this URL and the 10 others I've attempted to load). Can you try disabling other extensions? (this was the culprit in #45)

**Comment by wfan2** [comment]
Was working fine but same thing happened to me today as well

Version 64.0.3282.167 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/28750579/36242709-79b1ca7e-1271-11e8-8a7a-95a159ca88ac.png)

**Comment by wfan2** [comment]
update - cleared cookies and working fine

**Comment by nextgens** [comment]
Hmmm. So it's either setting the cookies in a way that the extension doesn't block (yet) ... or you have disabled it for a bit, got the paywall and re-enabling it doesn't fix it...

Either ways, the solution is to force-flush the cookies... which I will look into doing in the version after the next

**Comment by nextgens** [comment]
@XeonNAS which country / type of network/ ip are you browsing it from? They might tweak the paywall logic based on the geo-location data

**Comment by wfan2** [comment]
Sounds good - I'm from Australia using ipv4

**Comment by dwoo4dwoo** [comment]
I fixed this problem by:
- installing EditThisCookie
- setting paywallCount to 1
- setting paywallCount as readonly
David

**Comment by XeonNAS** [comment]
I've received a new laptop today with Windows 10 and the extension seems to be working fine. Please close.
