### ISSUE TITLE
The Times has Stopped working on Firefox

### ISSUE THREAD

**Issue by defrilitus** [nextgens/anti-paywall#45]
_The Times_ (https://www.thetimes.co.uk) has stopped working on Firefox (actually Waterfox), but is fine on Chrome. I'm using both on a Mac,

**Comment by nextgens** [comment]
Hmm, I can't reproduce it. If you use an private window in firefox (File->new private window), does it work?

Do you have a specific URL/article for me to try?

**Comment by defrilitus** [comment]
You are right. After your comment above, I tested Anti-Paywall with all my other extensions; [User-Agent Switcher 0.1.4](https://add0n.com/useragent-switcher.html) was creating a conflict. Removing it returned Anti-Paywall to normal. Case closed. Apologies.
