### ISSUE TITLE
chrome Anti-Paywall extension now RS?

### ISSUE THREAD

**Issue by GoodoBill** [nextgens/anti-paywall#65]
Hi Folks, Both PC's have had a Chrome update now to Version 65.0.3325.146. The extension I was using for accessing mainly Ozzy news has gone. When I used an old link to access The Chrome store I get Error 404 page.  Will this be coming back for Chrome or do we have to switch browsers to Firefox?  I did this temporarily for one and it seemed to be an add on and worked on all the same newspapers. 

Would love it if someone could check this out as it worked great.

Regards  Bill

**Comment by nextgens** [comment]
It was pulled by google: see #67 for details.

You can still install the extension using the developer settings (without the market)
