### ISSUE TITLE
Chrome extension removed from Store

### ISSUE THREAD

**Issue by Toriigate** [nextgens/anti-paywall#67]
As the title says, the Chrome extension is no longer available via the Chrome Store.

**Comment by nextgens** [comment]
It was pulled by google for "policy violation". I won't be re-uploading it there until it changes...

So complain to google and get them to change their policy ;)

**Comment by Toriigate** [comment]
To be honest, I'm using Firefox most of the time... :P

Thanks!

**Comment by jeroenev** [comment]
why not just add a .crx file for download to github?
also it seems like other paywall bypassers are still available for chrome, so not sure why yours would be blocked
