### ISSUE TITLE
Chrome Extension missing

### ISSUE THREAD

**Issue by XmansGhost** [nextgens/anti-paywall#68]
![image](https://user-images.githubusercontent.com/32760609/37521968-7ac68fd8-2948-11e8-89dd-7f00d2f2cecd.png)
This is what i get when i use the link,It is not available on the store itself. It would be better if u just gave the crx file to copy and paste in the extensions folder of chrome.

**Comment by nextgens** [comment]
That's the plan for next release.

#67 for why it's necessary

**Comment by XmansGhost** [comment]
Never Mind i will wait or use firefox only. Thanks for the addon tho.
