### ISSUE TITLE
Basilisk reports the extension is corrupt and cannot be installed

### ISSUE THREAD

**Issue by Telmesomething** [nextgens/anti-paywall#7]
[Basilisk](https://www.basilisk-browser.org/) displays a message that the extension is corrupt and cannot be installed. Here's a screenshot of it:

![anti-paywall_corrupt](https://user-images.githubusercontent.com/33827636/33881736-0375c6a8-df36-11e7-92be-eb43ed50f3b8.PNG)

**Comment by nextgens** [comment]
Basilisk is not supported; If you can provide a patch I will merge it, but otherwise you are on your own :)

**Comment by Telmesomething** [comment]
Is it possible to edit your manifest.json by adding the following code to it? 

`  "short_name": "Anti-Paywall",
  "applications": {
    "gecko": {
      "id": "addon@https://addons.mozilla.org/en-US/firefox/addon/anti-paywall/"
    }
  }`

There's a tip on the Pale Moon/Basilisk forum to [edit the manifest.json](https://forum.palemoon.org/viewtopic.php?f=61&t=17664) and I was wondering whether that would offer a solution to the problem of not being able to install it on Basilisk.
