### ISSUE TITLE
Chrome browser--can't get extension

### ISSUE THREAD

**Issue by hammberry** [nextgens/anti-paywall#76]
When I try
https://chrome.google.com/webstore/detail/anti-paywall/likpiciaabojkjnaigjfhgdfokcahooc

I get
404. That’s an error.

The requested URL was not found on this server. That’s all we know.

**Comment by Lynnyx** [comment]
Second that. Please provide an alternate download location.

**Comment by Lynnyx** [comment]
I actually managed to package the installer for chrome, though it won't auto-update as you haven't downloaded it from the store. You can dowload the file, then open chrome://extensions/ in chrome and drag the downloaded file onto the extensions page.

Download link: http://s000.tinyupload.com/?file_id=58851926925550570871

**Comment by hammberry** [comment]
Thanks so much. This works. Now I need some way to finding when the extension updates so I can download the new version.

**Comment by Lynnyx** [comment]
I think it would be possible to auto-update the extension if it would be bundled with a pre-configured chrome install like under 'Force-installing using master_preferences' in https://support.google.com/chrome/a/answer/188453

The extension would have to be hosted somewhere outside of the chrome web store though.

**Comment by geor93** [comment]
The download link is dead. Where can a Chrome user get this extension, nowadays?

**Comment by nextgens** [comment]
You can grab the XPI file from the release page... and rename it to a .crx

**Comment by nextgens** [comment]
I'm going to close this bug and track it on #110
