### ISSUE TITLE
Google no longer available?

### ISSUE THREAD

**Issue by Frederikalan** [nextgens/anti-paywall#99]
https://chrome.google.com/webstore/detail/anti-paywall/likpiciaabojkjnaigjfhgdfokcahooc is the error message when accessing playstore?

**Comment by Frederikalan** [comment]
I mean C hrom not Google

**Comment by Frederikalan** [comment]
Chrome

**Comment by ekaggata** [comment]
Just clone the whole repository (or download it as a zip file and unpack it somewhere), navigate to chrome://extensions/, turn the developer mode on (the switch is in the top-right corner), click the "load unpacked" button in the top left corner and choose the directory where you have cloned/unpacked the extension. Works just fine in Google Chrome 69.0.3497.100 on Linux.

**Comment by QasimQureshi** [comment]
The Mozilla link doesn't work either - https://addons.mozilla.org/addon/anti-paywall

Any word on how to use still make it work?

**Comment by nextgens** [comment]
This is a dup of #76
